// Auto-generated from real DartsLive API match data
// Game performances across all 13 Thirstday@DB matches

import type { GameFormat, GameFormatCategory } from './types';

export interface SeedGamePerformance {
  playerName: string;
  gameId: number;
  gameType: GameFormat;
  format: GameFormatCategory;
  partnerNames: string[];
  won: boolean;
  legsWon: number;
  legsLost: number;
  stats01: number;
  statsCricket: number;
}

// Real per-game performance data from DartsLive API
export const REAL_GAME_PERFORMANCES: SeedGamePerformance[] = [
  // Match 1 — 2026-02-12
  { playerName: 'Tan Li Ting', gameId: 1, gameType: 'singles', format: '01', partnerNames: [], won: false, legsWon: 0, legsLost: 2, stats01: 92.62, statsCricket: 3.5 },
  { playerName: 'Clarence Yeo WG', gameId: 2, gameType: 'singles', format: 'mixed', partnerNames: [], won: false, legsWon: 1, legsLost: 2, stats01: 90.02, statsCricket: 4.04 },
  { playerName: 'Ang Keng Yeow', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Wang GuanFei'], won: true, legsWon: 2, legsLost: 1, stats01: 99.41, statsCricket: 2.73 },
  { playerName: 'Wang GuanFei', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Ang Keng Yeow'], won: true, legsWon: 2, legsLost: 1, stats01: 89.0, statsCricket: 4.5 },
  { playerName: 'Tan Li Ting', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Jack Li'], won: true, legsWon: 2, legsLost: 1, stats01: 92.62, statsCricket: 3.5 },
  { playerName: 'Jack Li', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Tan Li Ting'], won: true, legsWon: 2, legsLost: 1, stats01: 78.58, statsCricket: 2.91 },
  { playerName: 'Clarence Yeo WG', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Wang GuanFei'], won: true, legsWon: 2, legsLost: 0, stats01: 90.02, statsCricket: 4.04 },
  { playerName: 'Wang GuanFei', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Clarence Yeo WG'], won: true, legsWon: 2, legsLost: 0, stats01: 89.0, statsCricket: 4.5 },
  { playerName: 'Tan Li Ting', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Wang GuanFei'], won: false, legsWon: 1, legsLost: 2, stats01: 92.62, statsCricket: 3.5 },
  { playerName: 'Wang GuanFei', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Tan Li Ting'], won: false, legsWon: 1, legsLost: 2, stats01: 89.0, statsCricket: 4.5 },
  { playerName: 'Clarence Yeo WG', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Ang Keng Yeow'], won: true, legsWon: 2, legsLost: 0, stats01: 90.02, statsCricket: 4.04 },
  { playerName: 'Ang Keng Yeow', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Clarence Yeo WG'], won: true, legsWon: 2, legsLost: 0, stats01: 99.41, statsCricket: 2.73 },
  { playerName: 'Clarence Yeo WG', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Ang Keng Yeow', 'Jack Li'], won: false, legsWon: 1, legsLost: 2, stats01: 90.02, statsCricket: 4.04 },
  { playerName: 'Ang Keng Yeow', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Clarence Yeo WG', 'Jack Li'], won: false, legsWon: 1, legsLost: 2, stats01: 99.41, statsCricket: 2.73 },
  { playerName: 'Jack Li', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Clarence Yeo WG', 'Ang Keng Yeow'], won: false, legsWon: 1, legsLost: 2, stats01: 78.58, statsCricket: 2.91 },
  { playerName: 'Clarence Yeo WG', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Ang Keng Yeow', 'Jack Li', 'Wang GuanFei'], won: true, legsWon: 1, legsLost: 0, stats01: 90.02, statsCricket: 4.04 },
  { playerName: 'Ang Keng Yeow', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Clarence Yeo WG', 'Jack Li', 'Wang GuanFei'], won: true, legsWon: 1, legsLost: 0, stats01: 99.41, statsCricket: 2.73 },
  { playerName: 'Jack Li', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Clarence Yeo WG', 'Ang Keng Yeow', 'Wang GuanFei'], won: true, legsWon: 1, legsLost: 0, stats01: 78.58, statsCricket: 2.91 },
  { playerName: 'Wang GuanFei', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Clarence Yeo WG', 'Ang Keng Yeow', 'Jack Li'], won: true, legsWon: 1, legsLost: 0, stats01: 89.0, statsCricket: 4.5 },
  // Match 2 — 2026-02-26
  { playerName: 'Ang Keng Yeow', gameId: 1, gameType: 'singles', format: '01', partnerNames: [], won: true, legsWon: 2, legsLost: 1, stats01: 83.82, statsCricket: 4.05 },
  { playerName: 'Clarence Yeo WG', gameId: 2, gameType: 'singles', format: 'mixed', partnerNames: [], won: true, legsWon: 2, legsLost: 1, stats01: 92.28, statsCricket: 3.8 },
  { playerName: 'Tan Li Ting', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Jack Li'], won: true, legsWon: 2, legsLost: 0, stats01: 83.66, statsCricket: 3.13 },
  { playerName: 'Jack Li', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Tan Li Ting'], won: true, legsWon: 2, legsLost: 0, stats01: 101.61, statsCricket: 3.09 },
  { playerName: 'Ang Keng Yeow', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Jack Li'], won: true, legsWon: 2, legsLost: 0, stats01: 83.82, statsCricket: 4.05 },
  { playerName: 'Jack Li', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Ang Keng Yeow'], won: true, legsWon: 2, legsLost: 0, stats01: 101.61, statsCricket: 3.09 },
  { playerName: 'Clarence Yeo WG', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Wang GuanFei'], won: true, legsWon: 2, legsLost: 1, stats01: 92.28, statsCricket: 3.8 },
  { playerName: 'Wang GuanFei', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Clarence Yeo WG'], won: true, legsWon: 2, legsLost: 1, stats01: 100.0, statsCricket: 2.78 },
  { playerName: 'Melvin Lee XC', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Wang GuanFei'], won: true, legsWon: 2, legsLost: 1, stats01: 75.52, statsCricket: 3.94 },
  { playerName: 'Wang GuanFei', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Melvin Lee XC'], won: true, legsWon: 2, legsLost: 1, stats01: 100.0, statsCricket: 2.78 },
  { playerName: 'Melvin Lee XC', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Tan Li Ting'], won: true, legsWon: 2, legsLost: 1, stats01: 75.52, statsCricket: 3.94 },
  { playerName: 'Tan Li Ting', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Melvin Lee XC'], won: true, legsWon: 2, legsLost: 1, stats01: 83.66, statsCricket: 3.13 },
  { playerName: 'Clarence Yeo WG', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Melvin Lee XC', 'Ang Keng Yeow'], won: true, legsWon: 2, legsLost: 1, stats01: 92.28, statsCricket: 3.8 },
  { playerName: 'Melvin Lee XC', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Clarence Yeo WG', 'Ang Keng Yeow'], won: true, legsWon: 2, legsLost: 1, stats01: 75.52, statsCricket: 3.94 },
  { playerName: 'Ang Keng Yeow', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Clarence Yeo WG', 'Melvin Lee XC'], won: true, legsWon: 2, legsLost: 1, stats01: 83.82, statsCricket: 4.05 },
  { playerName: 'Clarence Yeo WG', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Melvin Lee XC', 'Wang GuanFei', 'Jack Li'], won: true, legsWon: 1, legsLost: 0, stats01: 92.28, statsCricket: 3.8 },
  { playerName: 'Melvin Lee XC', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Clarence Yeo WG', 'Wang GuanFei', 'Jack Li'], won: true, legsWon: 1, legsLost: 0, stats01: 75.52, statsCricket: 3.94 },
  { playerName: 'Wang GuanFei', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Clarence Yeo WG', 'Melvin Lee XC', 'Jack Li'], won: true, legsWon: 1, legsLost: 0, stats01: 100.0, statsCricket: 2.78 },
  { playerName: 'Jack Li', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Clarence Yeo WG', 'Melvin Lee XC', 'Wang GuanFei'], won: true, legsWon: 1, legsLost: 0, stats01: 101.61, statsCricket: 3.09 },
  // Match 3 — 2026-03-05
  { playerName: 'Melvin Lee XC', gameId: 1, gameType: 'singles', format: '01', partnerNames: [], won: true, legsWon: 2, legsLost: 0, stats01: 115.26, statsCricket: 4.44 },
  { playerName: 'Clarence Yeo WG', gameId: 2, gameType: 'singles', format: 'mixed', partnerNames: [], won: true, legsWon: 2, legsLost: 1, stats01: 103.11, statsCricket: 3.69 },
  { playerName: 'Wang GuanFei', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: [], won: true, legsWon: 2, legsLost: 1, stats01: 90.16, statsCricket: 2.79 },
  { playerName: 'Clarence Yeo WG', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Jack Li'], won: true, legsWon: 2, legsLost: 0, stats01: 103.11, statsCricket: 3.69 },
  { playerName: 'Jack Li', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Clarence Yeo WG'], won: true, legsWon: 2, legsLost: 0, stats01: 121.5, statsCricket: 2.8 },
  { playerName: 'Clarence Yeo WG', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Melvin Lee XC'], won: true, legsWon: 2, legsLost: 0, stats01: 103.11, statsCricket: 3.69 },
  { playerName: 'Melvin Lee XC', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Clarence Yeo WG'], won: true, legsWon: 2, legsLost: 0, stats01: 115.26, statsCricket: 4.44 },
  { playerName: 'Tan Li Ting', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Anonymous'], won: false, legsWon: 1, legsLost: 2, stats01: 105.25, statsCricket: 3.0 },
  { playerName: 'Anonymous', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Tan Li Ting'], won: false, legsWon: 1, legsLost: 2, stats01: 0, statsCricket: 0 },
  { playerName: 'Wang GuanFei', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Melvin Lee XC'], won: true, legsWon: 2, legsLost: 0, stats01: 90.16, statsCricket: 2.79 },
  { playerName: 'Melvin Lee XC', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Wang GuanFei'], won: true, legsWon: 2, legsLost: 0, stats01: 115.26, statsCricket: 4.44 },
  { playerName: 'Wang GuanFei', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Tan Li Ting'], won: true, legsWon: 2, legsLost: 0, stats01: 90.16, statsCricket: 2.79 },
  { playerName: 'Tan Li Ting', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Wang GuanFei'], won: true, legsWon: 2, legsLost: 0, stats01: 105.25, statsCricket: 3.0 },
  { playerName: 'Wang GuanFei', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Tan Li Ting', 'Jack Li'], won: true, legsWon: 1, legsLost: 0, stats01: 90.16, statsCricket: 2.79 },
  { playerName: 'Tan Li Ting', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Wang GuanFei', 'Jack Li'], won: true, legsWon: 1, legsLost: 0, stats01: 105.25, statsCricket: 3.0 },
  { playerName: 'Jack Li', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Wang GuanFei', 'Tan Li Ting'], won: true, legsWon: 1, legsLost: 0, stats01: 121.5, statsCricket: 2.8 },
  // Match 4 — 2026-03-12
  { playerName: 'Melvin Lee XC', gameId: 1, gameType: 'singles', format: '01', partnerNames: [], won: false, legsWon: 1, legsLost: 2, stats01: 82.87, statsCricket: 0.0 },
  { playerName: 'Clarence Yeo WG', gameId: 2, gameType: 'singles', format: 'mixed', partnerNames: [], won: false, legsWon: 0, legsLost: 2, stats01: 105.0, statsCricket: 2.83 },
  { playerName: 'Ang Keng Yeow', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Jack Li'], won: false, legsWon: 0, legsLost: 2, stats01: 77.33, statsCricket: 1.75 },
  { playerName: 'Jack Li', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Ang Keng Yeow'], won: false, legsWon: 0, legsLost: 2, stats01: 92.95, statsCricket: 2.87 },
  { playerName: 'Tan Li Ting', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: [], won: true, legsWon: 2, legsLost: 0, stats01: 88.96, statsCricket: 2.83 },
  { playerName: 'Clarence Yeo WG', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: [], won: false, legsWon: 0, legsLost: 2, stats01: 105.0, statsCricket: 2.83 },
  { playerName: 'Melvin Lee XC', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Wang GuanFei'], won: false, legsWon: 0, legsLost: 2, stats01: 82.87, statsCricket: 0.0 },
  { playerName: 'Wang GuanFei', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Melvin Lee XC'], won: false, legsWon: 0, legsLost: 2, stats01: 85.22, statsCricket: 0.33 },
  { playerName: 'Clarence Yeo WG', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Tan Li Ting'], won: false, legsWon: 1, legsLost: 2, stats01: 105.0, statsCricket: 2.83 },
  { playerName: 'Tan Li Ting', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Clarence Yeo WG'], won: false, legsWon: 1, legsLost: 2, stats01: 88.96, statsCricket: 2.83 },
  { playerName: 'Wang GuanFei', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Jack Li'], won: false, legsWon: 1, legsLost: 2, stats01: 85.22, statsCricket: 0.33 },
  { playerName: 'Jack Li', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Wang GuanFei'], won: false, legsWon: 1, legsLost: 2, stats01: 92.95, statsCricket: 2.87 },
  { playerName: 'Tan Li Ting', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Melvin Lee XC', 'Wang GuanFei', 'Jack Li'], won: false, legsWon: 0, legsLost: 1, stats01: 88.96, statsCricket: 2.83 },
  { playerName: 'Melvin Lee XC', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Tan Li Ting', 'Wang GuanFei', 'Jack Li'], won: false, legsWon: 0, legsLost: 1, stats01: 82.87, statsCricket: 0.0 },
  { playerName: 'Wang GuanFei', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Tan Li Ting', 'Melvin Lee XC', 'Jack Li'], won: false, legsWon: 0, legsLost: 1, stats01: 85.22, statsCricket: 0.33 },
  { playerName: 'Jack Li', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Tan Li Ting', 'Melvin Lee XC', 'Wang GuanFei'], won: false, legsWon: 0, legsLost: 1, stats01: 92.95, statsCricket: 2.87 },
  // Match 5 — 2026-03-19
  { playerName: 'Jack Li', gameId: 1, gameType: 'singles', format: '01', partnerNames: [], won: false, legsWon: 0, legsLost: 2, stats01: 67.78, statsCricket: 4.0 },
  { playerName: 'Clarence Yeo WG', gameId: 2, gameType: 'singles', format: 'mixed', partnerNames: [], won: true, legsWon: 2, legsLost: 1, stats01: 91.0, statsCricket: 3.57 },
  { playerName: 'Melvin Lee XC', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Ang Keng Yeow'], won: true, legsWon: 2, legsLost: 1, stats01: 90.0, statsCricket: 3.18 },
  { playerName: 'Ang Keng Yeow', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Melvin Lee XC'], won: true, legsWon: 2, legsLost: 1, stats01: 99.21, statsCricket: 3.14 },
  { playerName: 'Clarence Yeo WG', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Tan Li Ting'], won: false, legsWon: 0, legsLost: 2, stats01: 91.0, statsCricket: 3.57 },
  { playerName: 'Tan Li Ting', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Clarence Yeo WG'], won: false, legsWon: 0, legsLost: 2, stats01: 67.55, statsCricket: 2.9 },
  { playerName: 'Clarence Yeo WG', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Melvin Lee XC'], won: false, legsWon: 1, legsLost: 2, stats01: 91.0, statsCricket: 3.57 },
  { playerName: 'Melvin Lee XC', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Clarence Yeo WG'], won: false, legsWon: 1, legsLost: 2, stats01: 90.0, statsCricket: 3.18 },
  { playerName: 'Ang Keng Yeow', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Wang GuanFei'], won: true, legsWon: 2, legsLost: 0, stats01: 99.21, statsCricket: 3.14 },
  { playerName: 'Wang GuanFei', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Ang Keng Yeow'], won: true, legsWon: 2, legsLost: 0, stats01: 78.0, statsCricket: 1.5 },
  { playerName: 'Ang Keng Yeow', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Wang GuanFei'], won: false, legsWon: 0, legsLost: 2, stats01: 99.21, statsCricket: 3.14 },
  { playerName: 'Wang GuanFei', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Ang Keng Yeow'], won: false, legsWon: 0, legsLost: 2, stats01: 78.0, statsCricket: 1.5 },
  { playerName: 'Melvin Lee XC', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Tan Li Ting', 'Jack Li'], won: true, legsWon: 2, legsLost: 0, stats01: 90.0, statsCricket: 3.18 },
  { playerName: 'Tan Li Ting', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Melvin Lee XC', 'Jack Li'], won: true, legsWon: 2, legsLost: 0, stats01: 67.55, statsCricket: 2.9 },
  { playerName: 'Jack Li', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Melvin Lee XC', 'Tan Li Ting'], won: true, legsWon: 2, legsLost: 0, stats01: 67.78, statsCricket: 4.0 },
  { playerName: 'Melvin Lee XC', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Tan Li Ting', 'Ang Keng Yeow', 'Wang GuanFei'], won: true, legsWon: 1, legsLost: 0, stats01: 90.0, statsCricket: 3.18 },
  { playerName: 'Tan Li Ting', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Melvin Lee XC', 'Ang Keng Yeow', 'Wang GuanFei'], won: true, legsWon: 1, legsLost: 0, stats01: 67.55, statsCricket: 2.9 },
  { playerName: 'Ang Keng Yeow', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Melvin Lee XC', 'Tan Li Ting', 'Wang GuanFei'], won: true, legsWon: 1, legsLost: 0, stats01: 99.21, statsCricket: 3.14 },
  { playerName: 'Wang GuanFei', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Melvin Lee XC', 'Tan Li Ting', 'Ang Keng Yeow'], won: true, legsWon: 1, legsLost: 0, stats01: 78.0, statsCricket: 1.5 },
  // Match 6 — 2026-04-09
  { playerName: 'Melvin Lee XC', gameId: 1, gameType: 'singles', format: '01', partnerNames: [], won: true, legsWon: 2, legsLost: 0, stats01: 101.25, statsCricket: 2.79 },
  { playerName: 'Clarence Yeo WG', gameId: 2, gameType: 'singles', format: 'mixed', partnerNames: [], won: false, legsWon: 1, legsLost: 2, stats01: 82.44, statsCricket: 3.24 },
  { playerName: 'Tan Li Ting', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Ang Keng Yeow'], won: true, legsWon: 2, legsLost: 1, stats01: 103.04, statsCricket: 2.5 },
  { playerName: 'Ang Keng Yeow', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Tan Li Ting'], won: true, legsWon: 2, legsLost: 1, stats01: 105.08, statsCricket: 2.55 },
  { playerName: 'Tan Li Ting', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Jack Li'], won: false, legsWon: 1, legsLost: 2, stats01: 103.04, statsCricket: 2.5 },
  { playerName: 'Jack Li', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Tan Li Ting'], won: false, legsWon: 1, legsLost: 2, stats01: 60.5, statsCricket: 1.0 },
  { playerName: 'Clarence Yeo WG', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Melvin Lee XC'], won: false, legsWon: 1, legsLost: 2, stats01: 82.44, statsCricket: 3.24 },
  { playerName: 'Melvin Lee XC', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Clarence Yeo WG'], won: false, legsWon: 1, legsLost: 2, stats01: 101.25, statsCricket: 2.79 },
  { playerName: 'Melvin Lee XC', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Wang GuanFei'], won: false, legsWon: 1, legsLost: 2, stats01: 101.25, statsCricket: 2.79 },
  { playerName: 'Wang GuanFei', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Melvin Lee XC'], won: false, legsWon: 1, legsLost: 2, stats01: 103.16, statsCricket: 3.0 },
  { playerName: 'Clarence Yeo WG', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Ang Keng Yeow'], won: false, legsWon: 1, legsLost: 2, stats01: 82.44, statsCricket: 3.24 },
  { playerName: 'Ang Keng Yeow', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Clarence Yeo WG'], won: false, legsWon: 1, legsLost: 2, stats01: 105.08, statsCricket: 2.55 },
  { playerName: 'Melvin Lee XC', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Tan Li Ting', 'Wang GuanFei'], won: false, legsWon: 1, legsLost: 2, stats01: 101.25, statsCricket: 2.79 },
  { playerName: 'Tan Li Ting', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Melvin Lee XC', 'Wang GuanFei'], won: false, legsWon: 1, legsLost: 2, stats01: 103.04, statsCricket: 2.5 },
  { playerName: 'Wang GuanFei', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Melvin Lee XC', 'Tan Li Ting'], won: false, legsWon: 1, legsLost: 2, stats01: 103.16, statsCricket: 3.0 },
  { playerName: 'Tan Li Ting', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Ang Keng Yeow', 'Wang GuanFei', 'Jack Li'], won: false, legsWon: 0, legsLost: 1, stats01: 103.04, statsCricket: 2.5 },
  { playerName: 'Ang Keng Yeow', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Tan Li Ting', 'Wang GuanFei', 'Jack Li'], won: false, legsWon: 0, legsLost: 1, stats01: 105.08, statsCricket: 2.55 },
  { playerName: 'Wang GuanFei', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Tan Li Ting', 'Ang Keng Yeow', 'Jack Li'], won: false, legsWon: 0, legsLost: 1, stats01: 103.16, statsCricket: 3.0 },
  { playerName: 'Jack Li', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Tan Li Ting', 'Ang Keng Yeow', 'Wang GuanFei'], won: false, legsWon: 0, legsLost: 1, stats01: 60.5, statsCricket: 1.0 },
  // Match 7 — 2026-04-16
  { playerName: 'Melvin Lee XC', gameId: 1, gameType: 'singles', format: '01', partnerNames: [], won: true, legsWon: 2, legsLost: 1, stats01: 81.02, statsCricket: 2.67 },
  { playerName: 'Clarence Yeo WG', gameId: 2, gameType: 'singles', format: 'mixed', partnerNames: [], won: true, legsWon: 2, legsLost: 0, stats01: 91.87, statsCricket: 3.44 },
  { playerName: 'Tan Li Ting', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Wang GuanFei'], won: true, legsWon: 2, legsLost: 0, stats01: 92.44, statsCricket: 3.35 },
  { playerName: 'Wang GuanFei', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Tan Li Ting'], won: true, legsWon: 2, legsLost: 0, stats01: 88.16, statsCricket: 2.75 },
  { playerName: 'Clarence Yeo WG', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Tan Li Ting'], won: true, legsWon: 2, legsLost: 0, stats01: 91.87, statsCricket: 3.44 },
  { playerName: 'Tan Li Ting', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Clarence Yeo WG'], won: true, legsWon: 2, legsLost: 0, stats01: 92.44, statsCricket: 3.35 },
  { playerName: 'Clarence Yeo WG', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Tan Li Ting'], won: true, legsWon: 2, legsLost: 1, stats01: 91.87, statsCricket: 3.44 },
  { playerName: 'Tan Li Ting', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Clarence Yeo WG'], won: true, legsWon: 2, legsLost: 1, stats01: 92.44, statsCricket: 3.35 },
  { playerName: 'Melvin Lee XC', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Wang GuanFei'], won: false, legsWon: 0, legsLost: 2, stats01: 81.02, statsCricket: 2.67 },
  { playerName: 'Wang GuanFei', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Melvin Lee XC'], won: false, legsWon: 0, legsLost: 2, stats01: 88.16, statsCricket: 2.75 },
  { playerName: 'Melvin Lee XC', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Jack Li'], won: false, legsWon: 0, legsLost: 2, stats01: 81.02, statsCricket: 2.67 },
  { playerName: 'Jack Li', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Melvin Lee XC'], won: false, legsWon: 0, legsLost: 2, stats01: 84.94, statsCricket: 2.66 },
  { playerName: 'Clarence Yeo WG', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Wang GuanFei', 'Jack Li'], won: false, legsWon: 1, legsLost: 2, stats01: 91.87, statsCricket: 3.44 },
  { playerName: 'Wang GuanFei', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Clarence Yeo WG', 'Jack Li'], won: false, legsWon: 1, legsLost: 2, stats01: 88.16, statsCricket: 2.75 },
  { playerName: 'Jack Li', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Clarence Yeo WG', 'Wang GuanFei'], won: false, legsWon: 1, legsLost: 2, stats01: 84.94, statsCricket: 2.66 },
  { playerName: 'Clarence Yeo WG', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Melvin Lee XC', 'Tan Li Ting', 'Jack Li'], won: false, legsWon: 0, legsLost: 1, stats01: 91.87, statsCricket: 3.44 },
  { playerName: 'Melvin Lee XC', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Clarence Yeo WG', 'Tan Li Ting', 'Jack Li'], won: false, legsWon: 0, legsLost: 1, stats01: 81.02, statsCricket: 2.67 },
  { playerName: 'Tan Li Ting', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Clarence Yeo WG', 'Melvin Lee XC', 'Jack Li'], won: false, legsWon: 0, legsLost: 1, stats01: 92.44, statsCricket: 3.35 },
  { playerName: 'Jack Li', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Clarence Yeo WG', 'Melvin Lee XC', 'Tan Li Ting'], won: false, legsWon: 0, legsLost: 1, stats01: 84.94, statsCricket: 2.66 },
  // Match 8 — 2026-04-23
  { playerName: 'Melvin Lee XC', gameId: 1, gameType: 'singles', format: '01', partnerNames: [], won: false, legsWon: 1, legsLost: 2, stats01: 91.51, statsCricket: 1.0 },
  { playerName: 'Clarence Yeo WG', gameId: 2, gameType: 'singles', format: 'mixed', partnerNames: [], won: true, legsWon: 2, legsLost: 1, stats01: 90.07, statsCricket: 3.4 },
  { playerName: 'Marcus Tan', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Ang Keng Yeow'], won: true, legsWon: 2, legsLost: 0, stats01: 99.67, statsCricket: 3.73 },
  { playerName: 'Ang Keng Yeow', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Marcus Tan'], won: true, legsWon: 2, legsLost: 0, stats01: 93.55, statsCricket: 3.86 },
  { playerName: 'Tan Li Ting', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Wang GuanFei'], won: false, legsWon: 0, legsLost: 2, stats01: 66.33, statsCricket: 2.86 },
  { playerName: 'Wang GuanFei', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Tan Li Ting'], won: false, legsWon: 0, legsLost: 2, stats01: 85.05, statsCricket: 2.8 },
  { playerName: 'Clarence Yeo WG', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Marcus Tan'], won: true, legsWon: 2, legsLost: 1, stats01: 90.07, statsCricket: 3.4 },
  { playerName: 'Marcus Tan', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Clarence Yeo WG'], won: true, legsWon: 2, legsLost: 1, stats01: 99.67, statsCricket: 3.73 },
  { playerName: 'Marcus Tan', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Tan Li Ting'], won: true, legsWon: 2, legsLost: 1, stats01: 99.67, statsCricket: 3.73 },
  { playerName: 'Tan Li Ting', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Marcus Tan'], won: true, legsWon: 2, legsLost: 1, stats01: 66.33, statsCricket: 2.86 },
  { playerName: 'Clarence Yeo WG', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Melvin Lee XC'], won: false, legsWon: 0, legsLost: 2, stats01: 90.07, statsCricket: 3.4 },
  { playerName: 'Melvin Lee XC', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Clarence Yeo WG'], won: false, legsWon: 0, legsLost: 2, stats01: 91.51, statsCricket: 1.0 },
  { playerName: 'Tan Li Ting', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Ang Keng Yeow', 'Wang GuanFei'], won: false, legsWon: 0, legsLost: 2, stats01: 66.33, statsCricket: 2.86 },
  { playerName: 'Ang Keng Yeow', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Tan Li Ting', 'Wang GuanFei'], won: false, legsWon: 0, legsLost: 2, stats01: 93.55, statsCricket: 3.86 },
  { playerName: 'Wang GuanFei', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Tan Li Ting', 'Ang Keng Yeow'], won: false, legsWon: 0, legsLost: 2, stats01: 85.05, statsCricket: 2.8 },
  { playerName: 'Ang Keng Yeow', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Melvin Lee XC', 'Wang GuanFei', 'Tan Li Ting'], won: false, legsWon: 0, legsLost: 1, stats01: 93.55, statsCricket: 3.86 },
  { playerName: 'Melvin Lee XC', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Ang Keng Yeow', 'Wang GuanFei', 'Tan Li Ting'], won: false, legsWon: 0, legsLost: 1, stats01: 91.51, statsCricket: 1.0 },
  { playerName: 'Wang GuanFei', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Ang Keng Yeow', 'Melvin Lee XC', 'Tan Li Ting'], won: false, legsWon: 0, legsLost: 1, stats01: 85.05, statsCricket: 2.8 },
  { playerName: 'Tan Li Ting', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Ang Keng Yeow', 'Melvin Lee XC', 'Wang GuanFei'], won: false, legsWon: 0, legsLost: 1, stats01: 66.33, statsCricket: 2.86 },
  // Match 9 — 2026-05-07
  { playerName: 'Melvin Lee XC', gameId: 1, gameType: 'singles', format: '01', partnerNames: [], won: false, legsWon: 1, legsLost: 2, stats01: 97.98, statsCricket: 2.75 },
  { playerName: 'Clarence Yeo WG', gameId: 2, gameType: 'singles', format: 'mixed', partnerNames: [], won: false, legsWon: 1, legsLost: 2, stats01: 102.47, statsCricket: 3.94 },
  { playerName: 'Marcus Tan', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Jack Li'], won: false, legsWon: 0, legsLost: 2, stats01: 45.33, statsCricket: 2.02 },
  { playerName: 'Jack Li', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Marcus Tan'], won: false, legsWon: 0, legsLost: 2, stats01: 69.75, statsCricket: 3.0 },
  { playerName: 'Clarence Yeo WG', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Ang Keng Yeow'], won: true, legsWon: 2, legsLost: 1, stats01: 102.47, statsCricket: 3.94 },
  { playerName: 'Ang Keng Yeow', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Clarence Yeo WG'], won: true, legsWon: 2, legsLost: 1, stats01: 95.91, statsCricket: 2.62 },
  { playerName: 'Clarence Yeo WG', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Marcus Tan'], won: false, legsWon: 1, legsLost: 2, stats01: 102.47, statsCricket: 3.94 },
  { playerName: 'Marcus Tan', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Clarence Yeo WG'], won: false, legsWon: 1, legsLost: 2, stats01: 45.33, statsCricket: 2.02 },
  { playerName: 'Melvin Lee XC', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Tan Li Ting'], won: false, legsWon: 1, legsLost: 2, stats01: 97.98, statsCricket: 2.75 },
  { playerName: 'Tan Li Ting', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Melvin Lee XC'], won: false, legsWon: 1, legsLost: 2, stats01: 97.67, statsCricket: 5.0 },
  { playerName: 'Tan Li Ting', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Wang GuanFei'], won: true, legsWon: 2, legsLost: 0, stats01: 97.67, statsCricket: 5.0 },
  { playerName: 'Wang GuanFei', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Tan Li Ting'], won: true, legsWon: 2, legsLost: 0, stats01: 99.66, statsCricket: 3.77 },
  { playerName: 'Melvin Lee XC', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Ang Keng Yeow', 'Wang GuanFei'], won: false, legsWon: 1, legsLost: 2, stats01: 97.98, statsCricket: 2.75 },
  { playerName: 'Ang Keng Yeow', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Melvin Lee XC', 'Wang GuanFei'], won: false, legsWon: 1, legsLost: 2, stats01: 95.91, statsCricket: 2.62 },
  { playerName: 'Wang GuanFei', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Melvin Lee XC', 'Ang Keng Yeow'], won: false, legsWon: 1, legsLost: 2, stats01: 99.66, statsCricket: 3.77 },
  { playerName: 'Melvin Lee XC', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Ang Keng Yeow', 'Jack Li', 'Wang GuanFei'], won: false, legsWon: 0, legsLost: 1, stats01: 97.98, statsCricket: 2.75 },
  { playerName: 'Ang Keng Yeow', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Melvin Lee XC', 'Jack Li', 'Wang GuanFei'], won: false, legsWon: 0, legsLost: 1, stats01: 95.91, statsCricket: 2.62 },
  { playerName: 'Jack Li', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Melvin Lee XC', 'Ang Keng Yeow', 'Wang GuanFei'], won: false, legsWon: 0, legsLost: 1, stats01: 69.75, statsCricket: 3.0 },
  { playerName: 'Wang GuanFei', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Melvin Lee XC', 'Ang Keng Yeow', 'Jack Li'], won: false, legsWon: 0, legsLost: 1, stats01: 99.66, statsCricket: 3.77 },
  // Match 10 — 2026-05-14
  { playerName: 'Melvin Lee XC', gameId: 1, gameType: 'singles', format: '01', partnerNames: [], won: true, legsWon: 2, legsLost: 0, stats01: 101.97, statsCricket: 3.23 },
  { playerName: 'Clarence Yeo WG', gameId: 2, gameType: 'singles', format: 'mixed', partnerNames: [], won: false, legsWon: 1, legsLost: 2, stats01: 83.69, statsCricket: 3.34 },
  { playerName: 'Ang Keng Yeow', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Marcus Tan'], won: true, legsWon: 2, legsLost: 0, stats01: 67.94, statsCricket: 3.21 },
  { playerName: 'Marcus Tan', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Ang Keng Yeow'], won: true, legsWon: 2, legsLost: 0, stats01: 61.12, statsCricket: 2.42 },
  { playerName: 'Tan Li Ting', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Jack Li'], won: true, legsWon: 2, legsLost: 1, stats01: 101.16, statsCricket: 4.67 },
  { playerName: 'Jack Li', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Tan Li Ting'], won: true, legsWon: 2, legsLost: 1, stats01: 70.41, statsCricket: 2.16 },
  { playerName: 'Clarence Yeo WG', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Melvin Lee XC'], won: true, legsWon: 2, legsLost: 1, stats01: 83.69, statsCricket: 3.34 },
  { playerName: 'Melvin Lee XC', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Clarence Yeo WG'], won: true, legsWon: 2, legsLost: 1, stats01: 101.97, statsCricket: 3.23 },
  { playerName: 'Marcus Tan', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Tan Li Ting'], won: false, legsWon: 1, legsLost: 2, stats01: 61.12, statsCricket: 2.42 },
  { playerName: 'Tan Li Ting', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Marcus Tan'], won: false, legsWon: 1, legsLost: 2, stats01: 101.16, statsCricket: 4.67 },
  { playerName: 'Clarence Yeo WG', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Ang Keng Yeow'], won: true, legsWon: 2, legsLost: 0, stats01: 83.69, statsCricket: 3.34 },
  { playerName: 'Ang Keng Yeow', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Clarence Yeo WG'], won: true, legsWon: 2, legsLost: 0, stats01: 67.94, statsCricket: 3.21 },
  { playerName: 'Melvin Lee XC', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Marcus Tan', 'Jack Li'], won: true, legsWon: 2, legsLost: 0, stats01: 101.97, statsCricket: 3.23 },
  { playerName: 'Marcus Tan', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Melvin Lee XC', 'Jack Li'], won: true, legsWon: 2, legsLost: 0, stats01: 61.12, statsCricket: 2.42 },
  { playerName: 'Jack Li', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Melvin Lee XC', 'Marcus Tan'], won: true, legsWon: 2, legsLost: 0, stats01: 70.41, statsCricket: 2.16 },
  { playerName: 'Melvin Lee XC', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Tan Li Ting', 'Ang Keng Yeow', 'Jack Li'], won: true, legsWon: 1, legsLost: 0, stats01: 101.97, statsCricket: 3.23 },
  { playerName: 'Tan Li Ting', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Melvin Lee XC', 'Ang Keng Yeow', 'Jack Li'], won: true, legsWon: 1, legsLost: 0, stats01: 101.16, statsCricket: 4.67 },
  { playerName: 'Ang Keng Yeow', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Melvin Lee XC', 'Tan Li Ting', 'Jack Li'], won: true, legsWon: 1, legsLost: 0, stats01: 67.94, statsCricket: 3.21 },
  { playerName: 'Jack Li', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Melvin Lee XC', 'Tan Li Ting', 'Ang Keng Yeow'], won: true, legsWon: 1, legsLost: 0, stats01: 70.41, statsCricket: 2.16 },
  // Match 11 — 2026-05-28
  { playerName: 'Melvin Lee XC', gameId: 1, gameType: 'singles', format: '01', partnerNames: [], won: true, legsWon: 2, legsLost: 0, stats01: 86.57, statsCricket: 3.55 },
  { playerName: 'Clarence Yeo WG', gameId: 2, gameType: 'singles', format: 'mixed', partnerNames: [], won: false, legsWon: 0, legsLost: 2, stats01: 88.83, statsCricket: 3.67 },
  { playerName: 'Wang GuanFei', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Ang Keng Yeow'], won: true, legsWon: 2, legsLost: 0, stats01: 97.12, statsCricket: 2.5 },
  { playerName: 'Ang Keng Yeow', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Wang GuanFei'], won: true, legsWon: 2, legsLost: 0, stats01: 96.37, statsCricket: 3.89 },
  { playerName: 'Melvin Lee XC', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Tan Li Ting'], won: false, legsWon: 1, legsLost: 2, stats01: 86.57, statsCricket: 3.55 },
  { playerName: 'Tan Li Ting', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Melvin Lee XC'], won: false, legsWon: 1, legsLost: 2, stats01: 88.61, statsCricket: 4.0 },
  { playerName: 'Clarence Yeo WG', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Melvin Lee XC'], won: true, legsWon: 2, legsLost: 1, stats01: 88.83, statsCricket: 3.67 },
  { playerName: 'Melvin Lee XC', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Clarence Yeo WG'], won: true, legsWon: 2, legsLost: 1, stats01: 86.57, statsCricket: 3.55 },
  { playerName: 'Tan Li Ting', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Wang GuanFei'], won: false, legsWon: 1, legsLost: 2, stats01: 88.61, statsCricket: 4.0 },
  { playerName: 'Wang GuanFei', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Tan Li Ting'], won: false, legsWon: 1, legsLost: 2, stats01: 97.12, statsCricket: 2.5 },
  { playerName: 'Clarence Yeo WG', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Ang Keng Yeow'], won: false, legsWon: 1, legsLost: 2, stats01: 88.83, statsCricket: 3.67 },
  { playerName: 'Ang Keng Yeow', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Clarence Yeo WG'], won: false, legsWon: 1, legsLost: 2, stats01: 96.37, statsCricket: 3.89 },
  { playerName: 'Clarence Yeo WG', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Melvin Lee XC', 'Ang Keng Yeow'], won: true, legsWon: 2, legsLost: 0, stats01: 88.83, statsCricket: 3.67 },
  { playerName: 'Melvin Lee XC', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Clarence Yeo WG', 'Ang Keng Yeow'], won: true, legsWon: 2, legsLost: 0, stats01: 86.57, statsCricket: 3.55 },
  { playerName: 'Ang Keng Yeow', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Clarence Yeo WG', 'Melvin Lee XC'], won: true, legsWon: 2, legsLost: 0, stats01: 96.37, statsCricket: 3.89 },
  { playerName: 'Clarence Yeo WG', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Melvin Lee XC', 'Tan Li Ting', 'Wang GuanFei'], won: false, legsWon: 0, legsLost: 1, stats01: 88.83, statsCricket: 3.67 },
  { playerName: 'Melvin Lee XC', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Clarence Yeo WG', 'Tan Li Ting', 'Wang GuanFei'], won: false, legsWon: 0, legsLost: 1, stats01: 86.57, statsCricket: 3.55 },
  { playerName: 'Tan Li Ting', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Clarence Yeo WG', 'Melvin Lee XC', 'Wang GuanFei'], won: false, legsWon: 0, legsLost: 1, stats01: 88.61, statsCricket: 4.0 },
  { playerName: 'Wang GuanFei', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Clarence Yeo WG', 'Melvin Lee XC', 'Tan Li Ting'], won: false, legsWon: 0, legsLost: 1, stats01: 97.12, statsCricket: 2.5 },
  // Match 12 — 2026-06-04
  { playerName: 'Melvin Lee XC', gameId: 1, gameType: 'singles', format: '01', partnerNames: [], won: true, legsWon: 2, legsLost: 1, stats01: 97.24, statsCricket: 3.5 },
  { playerName: 'Clarence Yeo WG', gameId: 2, gameType: 'singles', format: 'mixed', partnerNames: [], won: false, legsWon: 0, legsLost: 2, stats01: 102.28, statsCricket: 3.07 },
  { playerName: 'Wang GuanFei', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Ang Keng Yeow'], won: false, legsWon: 0, legsLost: 2, stats01: 68.7, statsCricket: 3.5 },
  { playerName: 'Ang Keng Yeow', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Wang GuanFei'], won: false, legsWon: 0, legsLost: 2, stats01: 62.87, statsCricket: 4.04 },
  { playerName: 'Melvin Lee XC', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Jack Li'], won: false, legsWon: 1, legsLost: 2, stats01: 97.24, statsCricket: 3.5 },
  { playerName: 'Jack Li', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Melvin Lee XC'], won: false, legsWon: 1, legsLost: 2, stats01: 77.93, statsCricket: 3.12 },
  { playerName: 'Clarence Yeo WG', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Ang Keng Yeow'], won: true, legsWon: 2, legsLost: 1, stats01: 102.28, statsCricket: 3.07 },
  { playerName: 'Ang Keng Yeow', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Clarence Yeo WG'], won: true, legsWon: 2, legsLost: 1, stats01: 62.87, statsCricket: 4.04 },
  { playerName: 'Wang GuanFei', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Marcus Tan'], won: false, legsWon: 0, legsLost: 2, stats01: 68.7, statsCricket: 3.5 },
  { playerName: 'Marcus Tan', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Wang GuanFei'], won: false, legsWon: 0, legsLost: 2, stats01: 103.25, statsCricket: 2.0 },
  { playerName: 'Clarence Yeo WG', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Tan Li Ting'], won: false, legsWon: 1, legsLost: 2, stats01: 102.28, statsCricket: 3.07 },
  { playerName: 'Tan Li Ting', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Clarence Yeo WG'], won: false, legsWon: 1, legsLost: 2, stats01: 60.66, statsCricket: 4.08 },
  { playerName: 'Melvin Lee XC', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Marcus Tan', 'Jack Li'], won: false, legsWon: 1, legsLost: 2, stats01: 97.24, statsCricket: 3.5 },
  { playerName: 'Marcus Tan', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Melvin Lee XC', 'Jack Li'], won: false, legsWon: 1, legsLost: 2, stats01: 103.25, statsCricket: 2.0 },
  { playerName: 'Jack Li', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Melvin Lee XC', 'Marcus Tan'], won: false, legsWon: 1, legsLost: 2, stats01: 77.93, statsCricket: 3.12 },
  { playerName: 'Ang Keng Yeow', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Tan Li Ting', 'Wang GuanFei', 'Jack Li'], won: true, legsWon: 1, legsLost: 0, stats01: 62.87, statsCricket: 4.04 },
  { playerName: 'Tan Li Ting', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Ang Keng Yeow', 'Wang GuanFei', 'Jack Li'], won: true, legsWon: 1, legsLost: 0, stats01: 60.66, statsCricket: 4.08 },
  { playerName: 'Wang GuanFei', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Ang Keng Yeow', 'Tan Li Ting', 'Jack Li'], won: true, legsWon: 1, legsLost: 0, stats01: 68.7, statsCricket: 3.5 },
  { playerName: 'Jack Li', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Ang Keng Yeow', 'Tan Li Ting', 'Wang GuanFei'], won: true, legsWon: 1, legsLost: 0, stats01: 77.93, statsCricket: 3.12 },
  // Match 13 — 2026-06-11
  { playerName: 'Melvin Lee XC', gameId: 1, gameType: 'singles', format: '01', partnerNames: [], won: true, legsWon: 2, legsLost: 1, stats01: 94.15, statsCricket: 3.83 },
  { playerName: 'Clarence Yeo WG', gameId: 2, gameType: 'singles', format: 'mixed', partnerNames: [], won: false, legsWon: 1, legsLost: 2, stats01: 85.03, statsCricket: 4.26 },
  { playerName: 'Tan Li Ting', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Jack Li'], won: true, legsWon: 2, legsLost: 0, stats01: 106.75, statsCricket: 3.17 },
  { playerName: 'Jack Li', gameId: 3, gameType: 'doubles', format: 'mixed', partnerNames: ['Tan Li Ting'], won: true, legsWon: 2, legsLost: 0, stats01: 70.08, statsCricket: 2.0 },
  { playerName: 'Melvin Lee XC', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Ang Keng Yeow'], won: false, legsWon: 1, legsLost: 2, stats01: 94.15, statsCricket: 3.83 },
  { playerName: 'Ang Keng Yeow', gameId: 4, gameType: 'doubles', format: 'mixed', partnerNames: ['Melvin Lee XC'], won: false, legsWon: 1, legsLost: 2, stats01: 90.04, statsCricket: 4.12 },
  { playerName: 'Clarence Yeo WG', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Wang GuanFei'], won: true, legsWon: 2, legsLost: 0, stats01: 85.03, statsCricket: 4.26 },
  { playerName: 'Wang GuanFei', gameId: 5, gameType: 'doubles', format: 'cricket', partnerNames: ['Clarence Yeo WG'], won: true, legsWon: 2, legsLost: 0, stats01: 87.83, statsCricket: 3.5 },
  { playerName: 'Melvin Lee XC', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Tan Li Ting'], won: false, legsWon: 1, legsLost: 2, stats01: 94.15, statsCricket: 3.83 },
  { playerName: 'Tan Li Ting', gameId: 6, gameType: 'doubles', format: 'half-it', partnerNames: ['Melvin Lee XC'], won: false, legsWon: 1, legsLost: 2, stats01: 106.75, statsCricket: 3.17 },
  { playerName: 'Clarence Yeo WG', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Ang Keng Yeow'], won: true, legsWon: 2, legsLost: 0, stats01: 85.03, statsCricket: 4.26 },
  { playerName: 'Ang Keng Yeow', gameId: 7, gameType: 'doubles', format: 'mixed', partnerNames: ['Clarence Yeo WG'], won: true, legsWon: 2, legsLost: 0, stats01: 90.04, statsCricket: 4.12 },
  { playerName: 'Clarence Yeo WG', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Melvin Lee XC', 'Wang GuanFei'], won: false, legsWon: 0, legsLost: 2, stats01: 85.03, statsCricket: 4.26 },
  { playerName: 'Melvin Lee XC', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Clarence Yeo WG', 'Wang GuanFei'], won: false, legsWon: 0, legsLost: 2, stats01: 94.15, statsCricket: 3.83 },
  { playerName: 'Wang GuanFei', gameId: 8, gameType: 'trios', format: 'mixed', partnerNames: ['Clarence Yeo WG', 'Melvin Lee XC'], won: false, legsWon: 0, legsLost: 2, stats01: 87.83, statsCricket: 3.5 },
  { playerName: 'Melvin Lee XC', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Wang GuanFei', 'Ang Keng Yeow', 'Jack Li'], won: false, legsWon: 0, legsLost: 1, stats01: 94.15, statsCricket: 3.83 },
  { playerName: 'Wang GuanFei', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Melvin Lee XC', 'Ang Keng Yeow', 'Jack Li'], won: false, legsWon: 0, legsLost: 1, stats01: 87.83, statsCricket: 3.5 },
  { playerName: 'Ang Keng Yeow', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Melvin Lee XC', 'Wang GuanFei', 'Jack Li'], won: false, legsWon: 0, legsLost: 1, stats01: 90.04, statsCricket: 4.12 },
  { playerName: 'Jack Li', gameId: 9, gameType: 'team', format: '01', partnerNames: ['Melvin Lee XC', 'Wang GuanFei', 'Ang Keng Yeow'], won: false, legsWon: 0, legsLost: 1, stats01: 70.08, statsCricket: 2.0 },
];